### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by Basilisvirus** [halfbyte/lcddogmspi#3]
Errors appear when i tried to implement this on arduino IDE and Atmel studio.
-First of all, WConstants.h need to be downloaded along with these files.
-In arduino ide it doesnt recognise all the pinMode(), digitalWrite(), and all the registers (SPDR register), the delay functions (nor the delay(), and neither the _delay_ms())
-In atmel studio 7 it show these errors, which im trying to fix:

undefined reference to `LCDdogmSPI::println(char*)'	gccpp_project	
undefined reference to `LCDdogmSPI::LCDdogmSPI(int, int, int)'	gccpp_project	
undefined reference to `LCDdogmSPI::init()'	gccpp_project	C:\Users\User\Documents\Atmel 
undefined reference to `LCDdogmSPI::cursorTo(int, int)'	gccpp_project	

How excatly is this library used?
Thanks

**Comment by halfbyte** [comment]
Hey, thanks for your report. I haven't used this library in ages (as you can tell by the time of the last commit) and it's probably not compatible with current versions of Arduino anymore. 

I currently don't have any time to dig into this, unfortunately. I'll put a notice about the status of this project into the description though. 

If you manage to get it working, let me know.

**Comment by Basilisvirus** [comment]
Ah, i see.
I managed to use the lcd, but using this tutorial and libraries:
https://www.lcd-module.com/support/application-note/arduino-meets-ea-dog.html

I also made a copy of the tutorial and libraries in my gitlab repo, with some extra instructions on how to make the project work:
https://gitlab.com/Basilisvirus/usefull-libraries-arduino-and-avr-c/tree/master/EA_DOGM163L_A

I tried to make your repo work. It looks promising and i could follow-up and fix some errors, but for a avr-c newbie like me, it would take me some time to fix all of it.

**Comment by halfbyte** [comment]
I understand and I am really sorry you ran into this. If I can find the time, I still have the DOGM module lying around somewhere and so I could try to update it, but I can't promise a time frame at all.

Thanks for taking the time for trying to fix it and reporting the problems, I really appreciate, even if I haven't looked at this in ages :)

**Comment by Basilisvirus** [comment]
Yeah, no problem. I always try to learn. I should have looked on the version of arduino IDE you made this on. Although i didnt expect the arduino IDE to change so much.
